/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EmulsifyProjectConfiguration {
  /**
   * Contains information about the Emulsify starter this project is based upon
   */
  starter: {
    /**
     * Git repository containing the starter this project is based upon
     */
    repository: string;
  };
  /**
   * Contains information about the Emulsify system this project is utilizing
   */
  system?: {
    /**
     * Git repository containing the system this project is utilizing
     */
    repository: string;
    /**
     * Commit, branch, or tag of the system this project is utilizing
     */
    checkout: string;
  };
}
